spring:
  application:
    name: gateway-server

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    resource-server:
      path: /resource-api/**
      url: http://localhost:8881
      stripPrefix: false
    auth-service:
      path: /user-api/**
      url: http://localhost:8882
      stripPrefix: false
    restaurant-service:
      path: /restaurant-api/**
      url: http://localhost:8883
      stripPrefix: false
    order-service:
      path: /order-api/**
      url: http://localhost:8884
      stripPrefix: false