/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.przemarcz.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7306565037011499582L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentAvro\",\"namespace\":\"com.przemarcz.avro\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"AddDelete\",\"symbols\":[\"ADD\",\"DEL\"]}},{\"name\":\"restaurantId\",\"type\":\"string\",\"logicalType\":\"UUID\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentAvro> ENCODER =
      new BinaryMessageEncoder<PaymentAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentAvro> DECODER =
      new BinaryMessageDecoder<PaymentAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PaymentAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private com.przemarcz.avro.AddDelete type;
   private java.lang.CharSequence restaurantId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentAvro() {}

  /**
   * All-args constructor.
   * @param type The new value for type
   * @param restaurantId The new value for restaurantId
   */
  public PaymentAvro(com.przemarcz.avro.AddDelete type, java.lang.CharSequence restaurantId) {
    this.type = type;
    this.restaurantId = restaurantId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return restaurantId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (com.przemarcz.avro.AddDelete)value$; break;
    case 1: restaurantId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public com.przemarcz.avro.AddDelete getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(com.przemarcz.avro.AddDelete value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'restaurantId' field.
   * @return The value of the 'restaurantId' field.
   */
  public java.lang.CharSequence getRestaurantId() {
    return restaurantId;
  }


  /**
   * Sets the value of the 'restaurantId' field.
   * @param value the value to set.
   */
  public void setRestaurantId(java.lang.CharSequence value) {
    this.restaurantId = value;
  }

  /**
   * Creates a new PaymentAvro RecordBuilder.
   * @return A new PaymentAvro RecordBuilder
   */
  public static com.przemarcz.avro.PaymentAvro.Builder newBuilder() {
    return new com.przemarcz.avro.PaymentAvro.Builder();
  }

  /**
   * Creates a new PaymentAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentAvro RecordBuilder
   */
  public static com.przemarcz.avro.PaymentAvro.Builder newBuilder(com.przemarcz.avro.PaymentAvro.Builder other) {
    if (other == null) {
      return new com.przemarcz.avro.PaymentAvro.Builder();
    } else {
      return new com.przemarcz.avro.PaymentAvro.Builder(other);
    }
  }

  /**
   * Creates a new PaymentAvro RecordBuilder by copying an existing PaymentAvro instance.
   * @param other The existing instance to copy.
   * @return A new PaymentAvro RecordBuilder
   */
  public static com.przemarcz.avro.PaymentAvro.Builder newBuilder(com.przemarcz.avro.PaymentAvro other) {
    if (other == null) {
      return new com.przemarcz.avro.PaymentAvro.Builder();
    } else {
      return new com.przemarcz.avro.PaymentAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentAvro>
    implements org.apache.avro.data.RecordBuilder<PaymentAvro> {

    private com.przemarcz.avro.AddDelete type;
    private java.lang.CharSequence restaurantId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.przemarcz.avro.PaymentAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[1].schema(), other.restaurantId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.przemarcz.avro.PaymentAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[1].schema(), other.restaurantId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public com.przemarcz.avro.AddDelete getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.przemarcz.avro.PaymentAvro.Builder setType(com.przemarcz.avro.AddDelete value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.przemarcz.avro.PaymentAvro.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'restaurantId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRestaurantId() {
      return restaurantId;
    }


    /**
      * Sets the value of the 'restaurantId' field.
      * @param value The value of 'restaurantId'.
      * @return This builder.
      */
    public com.przemarcz.avro.PaymentAvro.Builder setRestaurantId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.restaurantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'restaurantId' field has been set.
      * @return True if the 'restaurantId' field has been set, false otherwise.
      */
    public boolean hasRestaurantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'restaurantId' field.
      * @return This builder.
      */
    public com.przemarcz.avro.PaymentAvro.Builder clearRestaurantId() {
      restaurantId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentAvro build() {
      try {
        PaymentAvro record = new PaymentAvro();
        record.type = fieldSetFlags()[0] ? this.type : (com.przemarcz.avro.AddDelete) defaultValue(fields()[0]);
        record.restaurantId = fieldSetFlags()[1] ? this.restaurantId : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentAvro>
    READER$ = (org.apache.avro.io.DatumReader<PaymentAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.type.ordinal());

    out.writeString(this.restaurantId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.type = com.przemarcz.avro.AddDelete.values()[in.readEnum()];

      this.restaurantId = in.readString(this.restaurantId instanceof Utf8 ? (Utf8)this.restaurantId : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.type = com.przemarcz.avro.AddDelete.values()[in.readEnum()];
          break;

        case 1:
          this.restaurantId = in.readString(this.restaurantId instanceof Utf8 ? (Utf8)this.restaurantId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










