apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      annotations:
        prometheus.io/path: "/user-api/actuator/prometheus"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8882"
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: auth-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8882
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  ports:
  - port: 8882
    protocol: TCP
  selector:
    app: auth-server
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-server-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_server_requests_seconds_count_sum_auth
        target:
          type: AverageValue
          averageValue: 500m
