apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      annotations:
        prometheus.io/path: "/order-api/actuator/prometheus"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8884"
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8884
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
  - port: 8884
    protocol: TCP
  selector:
    app: order-service
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_server_requests_seconds_count_sum_order
        target:
          type: AverageValue
          averageValue: 500m