apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      annotations:
        prometheus.io/path: "/restaurant-api/actuator/prometheus"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8883"
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: restaurant-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8883
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
spec:
  ports:
  - port: 8883
    protocol: TCP
  selector:
    app: restaurant-service
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: restaurant-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restaurant-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_server_requests_seconds_count_sum_restaurant
        target:
          type: AverageValue
          averageValue: 500m