/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.przemarcz.avro;
@org.apache.avro.specific.AvroGenerated
public enum RestaurantDo implements org.apache.avro.generic.GenericEnumSymbol<RestaurantDo> {
  ADD, DEL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RestaurantDo\",\"namespace\":\"com.przemarcz.avro\",\"symbols\":[\"ADD\",\"DEL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
