/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.przemarcz.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentMethod implements org.apache.avro.generic.GenericEnumSymbol<PaymentMethod> {
  CASH, ONLINE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentMethod\",\"namespace\":\"com.przemarcz.avro\",\"symbols\":[\"CASH\",\"ONLINE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
