spring:
  profiles:
    profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
server:
  port: 8888

---

spring:
  profiles:
    profiles: k8s
    include: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config-k8s/
server:
  port: 8888