package com.przemarcz.restaurant.model.enums;

public enum RestaurantCategory {
    STREET_FOOD, SUSHI, PIZZA, BURGER, PASTA, KEBAB, VEGE, FIT, FISH, SEAFOOD, THAI_CUISINE, TURKISH_CUISINE, POLISH_CUISINE, MAXICAN_CUISINE, VIETNAMSE_CUISINE
}